accounts/urls.py
from django.urls import path
from .views import (
    LoginView,
    LogoutView,
    RegisterView,
    UserDetailView,
    UserUpdateView,
    UserPasswordChangeView
)

app_name = 'accounts'

urlpatterns = [
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('register', RegisterView.as_view(), name='user_registration'),
    path('<int:pk>', UserDetailView.as_view(), name='user_detail'),
    path('<int:pk>/update/', UserUpdateView.as_view(), name='user_update'),
    path('password_change/', UserPasswordChangeView.as_view(), name='user_password_change'),
]

api_v1/urls.py
from django.urls import path, include

import api_v1.views as views
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token


router = routers.DefaultRouter()
router.register('articles', views.ArticleViewSet)
router.register('authors', views.AuthorViewSet)

app_name = 'api_v1'


urlpatterns = [
    path('', include(router.urls)),
    path('login/', obtain_auth_token, name='api_token_auth'),
    path('logout/', views.LogoutView.as_view(), name='api_token_delete'),
]

source/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import IndexView, index_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index_view, name='main'),
    path('articles/', include('articles.urls.article_urls')),
    path('author/', include('articles.urls.author_urls')),
    path('genre/', include('articles.urls.genre_urls')),
    path('accounts/', include('accounts.urls')),
    path('api/v1/', include('api_v1.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(
        get_user_model(),
        related_name='profile',
        on_delete=models.CASCADE,
        verbose_name='Пользователь'
    )
    birthdate = models.DateField(null=True, blank=True, verbose_name='Дата рождения')
    avatar = models.ImageField(
        null=True,
        blank=True,
        upload_to='user_pics',
        verbose_name='Аватар'
    )

    def __str__(self):
        return self.user.get_full_name()

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth.models import User

from accounts.models import Profile


class RegisterForm(forms.ModelForm):
    password = forms.CharField(
        label='Пароль',
        required=True,
        strip=False,
        widget=forms.PasswordInput()
    )
    password_confirm = forms.CharField(
        label='Подтверждение пароля',
        required=True,
        strip=False,
        widget=forms.PasswordInput()
    )

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Введенные пароли не совпадают')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data.get('password'))
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = [
            'username',
            'password',
            'password_confirm',
            'first_name',
            'last_name',
            'email'
        ]


class DjangoRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'username',
            'password1',
            'password2',
            'first_name',
            'last_name',
            'email'
        ]
        field_classes = {'username': UsernameField}


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
            'email': 'Email'
        }


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user']


class PasswordChangeForm(forms.ModelForm):
    old_password = forms.CharField(label='Старый пароль', strip=False, widget=forms.PasswordInput)
    password = forms.CharField(label='Новый пароль', strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label='Подтверждение пароля', strip=False, widget=forms.PasswordInput)

    def clean_password_confirm(self):
        password = self.cleaned_data.get('password')
        password_confirm = self.cleaned_data.get('password_confirm')

        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают!')
        return password_confirm

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')

        if not self.instance.check_password(old_password):
            raise forms.ValidationError('Старый пароль неправильный!')
        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data.get('password'))
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields = ['old_password', 'password', 'password_confirm']

accounts/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model, update_session_auth_hash
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from django.views.generic import CreateView, DetailView, UpdateView

from .forms import DjangoRegisterForm, UserUpdateForm, ProfileUpdateForm, PasswordChangeForm
from .models import Profile


class LoginView(View):
    def get(self, request, *args, **kwargs):
        return render(request, template_name='accounts/login.html')

    def post(self, request, *args, **kwargs):
        context = {}
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            next = request.GET.get('next')
            if next:
                return redirect(next)
            return redirect('main')
        else:
            context['has_error'] = True
        return render(request, template_name='accounts/login.html', context=context)


class LogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        next = request.GET.get('next')
        if next:
            return redirect(next)
        return redirect('accounts:login')


class RegisterView(CreateView):
    model = User
    template_name = 'accounts/registration.html'
    form_class = DjangoRegisterForm

    def form_valid(self, form):
        user = form.save()
        Profile.objects.create(user=user)
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next = self.request.GET.get('next')
        if not next:
            next = self.request.POST.get('next')
        if not next:
            next = reverse('main')
        return next


class UserDetailView(LoginRequiredMixin, DetailView):
    model = get_user_model()
    template_name = 'accounts/user_detail.html'
    context_object_name = 'user_obj'
    paginate_by = 5
    paginate_orphans = 0
    
    def get_context_data(self, **kwargs):
        articles = self.object.article.order_by('-created_at')
        paginator = Paginator(articles, self.paginate_by, orphans=self.paginate_orphans)
        page_number = self.request.GET.get('page', 1)
        page = paginator.get_page(page_number)
        kwargs['page_obj'] = page
        kwargs['articles'] = page.object_list
        kwargs['is_paginated'] = page.has_other_pages()
        return super().get_context_data(**kwargs)


class UserUpdateView(UserPassesTestMixin, UpdateView):
    model = get_user_model()
    form_class = UserUpdateForm
    template_name = 'accounts/update.html'
    context_object_name = 'user_obj'

    def get_context_data(self, **kwargs):
        if 'profile_form' not in kwargs:
            kwargs['profile_form'] = self.get_profile_form()
        return super().get_context_data(**kwargs)

    def get_profile_form(self):
        form_kwargs = {'instance': self.object.profile}
        if self.request.method == 'POST':
            form_kwargs['data'] = self.request.POST
            form_kwargs['files'] = self.request.FILES
        return ProfileUpdateForm(**form_kwargs)

    def get_success_url(self):
        return reverse('accounts:user_detail', kwargs={'pk': self.object.pk})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        profile_form = self.get_profile_form()
        if form.is_valid() and profile_form.is_valid():
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)

    def form_valid(self, form, profile_form):
        response = super().form_valid(form)
        profile_form.save()
        return response

    def form_invalid(self, form, profile_form):
        context = self.get_context_data(form=form, profile_form=profile_form)
        return self.render_to_response(context)

    def test_func(self):
        return self.request.user == self.get_object()


class UserPasswordChangeView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    template_name = 'accounts/user_password_change.html'
    form_class = PasswordChangeForm
    context_object_name = 'user_obj'

    def get_success_url(self):
        return reverse('accounts:user_detail', kwargs={'pk': self.object.pk})

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        user = form.save()
        update_session_auth_hash(self.request, user)
        return HttpResponseRedirect(self.get_success_url())

templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
    <form action="{% url 'accounts:login' %}?next={{ request.GET.next }}" method="POST">
        {% csrf_token %}
        <h1>Войти</h1>
        <div style="width: 20rem;">
            <div class="mb-3 row">
                <label for="username" class="col-sm-2 col-form-label">Логин</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="username" name="username">
                </div>
            </div>
            <div class="mb-3 row">
                <label for="password" class="col-sm-2 col-form-label">Пароль</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control" id="password" name="password">
                </div>
            </div>
        </div>

        <button type="submit" class="btn btn-light">Войти</button>
    </form>
{% endblock %}

templates/accounts/registration.html
{% extends 'base.html' %}

{% block content %}
    <h1>Регистрация</h1>
    <form action="{% url 'accounts:user_registration' %}?next={{ request.GET.next }}" method="POST">
        {% csrf_token %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">{{ error }}</div>
        {% endfor %}

        <div class="mb-3">
            <label for="username" class="form-label">Логин</label>
            <input type="text" class="form-control" id="username" name="username" placeholder="Введите логин">
            {% for error in form.username.errors %}
                <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="mb-3">
            <label for="first_name" class="form-label">Имя</label>
            <input type="text" class="form-control" id="first_name" name="first_name" placeholder="Введите имя">
            {% for error in form.first_name.errors %}
                <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="mb-3">
            <label for="last_name" class="form-label">Фамилия</label>
            <input type="text" class="form-control" id="last_name" name="last_name" placeholder="Введите фамилию">
            {% for error in form.last_name.errors %}
                <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="mb-3">
            <label for="email" class="form-label">Email</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="name@example.com">
            {% for error in form.email.errors %}
                <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">Пароль</label>
            <input type="password" class="form-control" id="password" name="password1" placeholder="Введите пароль">
            {% for error in form.password1.errors %}
                <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="mb-3">
            <label for="password_confirm" class="form-label">Подтвердите пароль</label>
            <input type="password" class="form-control" id="password_confirm" name="password2" placeholder="Введите пароль еще раз">
            {% for error in form.password2.errors %}
                <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>

        <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
    </form>
{% endblock %}

templates/accounts/update.html
{% extends 'base.html' %}

{% block menu_links %}
    <li><a href="{% url 'accounts:user_detail' user_obj.pk %}">Назад</a></li>
    <li><a href="{% url 'accounts:user_password_change' %}">Смена пароля</a></li>
{% endblock %}

{% block content %}
    <div>
        <form
                action="{% url 'accounts:user_update' user_obj.pk %}"
                method="POST"
                enctype="multipart/form-data"
        >
            {% csrf_token %}
            {% include 'partial/forms.html' with form=form fields_only=True %}
            {% include 'partial/forms.html' with form=profile_form fields_only=True %}

            <button class="btn btn-primary" type="submit">Сохранить</button>
        </form>
    </div>
{% endblock %}

templates/accounts/user_detail.html
{% extends 'base.html' %}

{% block menu_links %}
    <li><a href="{% url 'accounts:user_update' user_obj.pk %}">Редактировать профиль</a></li>
    <li><a href="{% url 'accounts:user_password_change' %}">Смена пароля</a></li>
{% endblock %}

{% block content %}
    <h1>
        Личный кабинет пользователя {{ user_obj.get_full_name|default:user_obj.username }}
    </h1>

    <div class="card" style="width: 25rem;">
        <div class="card-body">
            {% if user_obj.profile.avatar %}
                <img src="{{ user_obj.profile.avatar.url }}" alt="avatar" width="250">
            {% endif %}
            <p class="card-text">Логин: {{ user_obj.username }}</p>
            <p class="card-text">Имя: {{ user_obj.first_name }}</p>
            <p class="card-text">Фамилия: {{ user_obj.last_name }}</p>
            <p class="card-text">Дата рождения: {{ user_obj.profile.birthdate }}</p>
            <p class="card-text">Эл. почта: {{ user_obj.email }}</p>
        </div>
    </div>

    <h3 class="mt-5">Статьи пользователя:</h3>
    <div class="mb-5">
        {% include 'partial/article_list.html' %}
    </div>
{% endblock %}

templates/accounts/user_password_change.html
{% extends 'base.html' %}

{% block menu_links %}
    <li><a href="{% url 'accounts:user_detail' user_obj.pk %}">Назад</a></li>
    <li><a href="{% url 'accounts:user_update' user_obj.pk %}">Редактировать профиль</a></li>
{% endblock %}

{% block content %}
    <h1>Смена пароля</h1>
    {% url 'accounts:user_password_change' as action_url %}
    {% include 'partial/forms.html' with action_url=action_url form_method='POST' %}
{% endblock %}