accounts/urls.py
from django.urls import path
from .views import (
    LoginView,
    LogoutView,
    RegisterView,
    UserDetailView,
    UserUpdateView,
    UserPasswordChangeView
)

app_name = 'accounts'

urlpatterns = [
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('register', RegisterView.as_view(), name='user_registration'),
    path('<int:pk>', UserDetailView.as_view(), name='user_detail'),
    path('<int:pk>/update/', UserUpdateView.as_view(), name='user_update'),
    path('password_change/', UserPasswordChangeView.as_view(), name='user_password_change'),
]

api_v1/urls.py
from django.urls import path, include

import api_v1.views as views
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token


router = routers.DefaultRouter()
router.register('articles', views.ArticleViewSet)
router.register('authors', views.AuthorViewSet)

app_name = 'api_v1'


urlpatterns = [
    path('', include(router.urls)),
    path('login/', obtain_auth_token, name='api_token_auth'),
    path('logout/', views.LogoutView.as_view(), name='api_token_delete'),
]

source/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import IndexView, index_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index_view, name='main'),
    path('articles/', include('articles.urls.article_urls')),
    path('author/', include('articles.urls.author_urls')),
    path('genre/', include('articles.urls.genre_urls')),
    path('accounts/', include('accounts.urls')),
    path('api/v1/', include('api_v1.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/views/author_views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from articles.forms import AuthorForm
from articles.models import Author


class AuthorCreateView(CreateView):
    model = Author
    template_name = 'authors/create.html'
    form_class = AuthorForm
    success_url = reverse_lazy('author_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['link'] = reverse('author_create')
        return context


class AuthorListView(ListView):
    template_name = 'authors/list.html'
    model = Author
    context_object_name = 'authors'
    paginate_by = 5
    paginate_orphans = 1


class AuthorUpdateView(UpdateView):
    model = Author
    template_name = 'authors/update.html'
    form_class = AuthorForm
    success_url = reverse_lazy('author_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['link'] = reverse('author_update', kwargs={'pk': self.kwargs.get('pk')})
        return context


class AuthorDeleteView(DeleteView):
    model = Author
    success_url = reverse_lazy('author_list')

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

templates/partial/article_list.html
{% if is_paginated %}
    {% include 'partial/pagination.html' %}
{% endif %}

<ul class="list-group">
    {% for article in articles %}
        <li class="list-group-item">
            <a href="{% url 'article_detail' article.pk %}">{{ article.title }}</a>
        </li>
    {% endfor %}
</ul>

templates/partial/author_form.html
<form action="{{ link }}" method="POST">
    {% csrf_token %}

    <div class="mb-3">
        <label for="first_name" class="form-label">Имя автора</label>
        {% if errors.first_name %}
            <input type="text" class="form-control" name="first_name" id="first_name" placeholder="Введите имя автора"
                   value="{{ author.first_name }}" style="border: 1px solid red">
            <div style="color: red; font-size: 10px">{{ errors.first_name }}</div>
        {% else %}
            <input type="text" class="form-control" name="first_name" id="first_name" placeholder="Введите имя автора"
                   value="{{ author.first_name }}" >
        {% endif %}
    </div>

    <div class="mb-3">
        <label for="last_name" class="form-label">Фамилия автора</label>
        {% if errors.last_name %}
            <input type="text" class="form-control" name="last_name" id="last_name" placeholder="Введите фамилию автора"
                   value="{{ author.last_name }}" style="border: 1px solid red" >
            <div style="color: red; font-size: 10px">{{ errors.last_name }}</div>
        {% else %}
            <input type="text" class="form-control" name="last_name" id="last_name" placeholder="Введите фамилию автора"
                   value="{{ author.last_name }}" >
        {% endif %}
    </div>

    <button type="submit" class="btn btn-success">{{ button_name }}</button>
    {% if button_name == 'Сохранить' %}
        <a href="{% url 'author_delete' author.pk %}" class="btn btn-danger">Удалить</a>
    {% endif %}
</form>

templates/partial/forms.html
{% if not fields_only %}
    <form action="{{ action_url }}" method="{{ form_method }}" enctype="multipart/form-data">
        {% csrf_token %}
{% endif %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">{{ error }}</div>
        {% endfor %}

        {% for field in form %}
            <div class="mb-3">
                {% for error in field.errors %}
                    <div class="text-danger">{{ error }}</div>
                {% endfor %}
                <div>{{ field.label }}</div>
                <div>{{ field }}</div>
            </div>
        {% endfor %}
{% if not fields_only %}
        <button class="btn btn-primary" type="submit">{{ button_text|default:"Сохранить" }}</button>
    </form>
{% endif %}

templates/partial/navigation.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'main' %}">MyBlog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'main' %}">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article_create' %}">Создать статью</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article_list' %}">Список статей</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'author_create' %}">Добавить автора</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'author_list' %}">Список авторов</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'genre_list' %}">Список жанров</a>
                </li>
                <li class="nav-item">
                    <button id="getArticles">Get articles</button>
                </li>

                {% if not request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="btn btn-info" href="{% url 'accounts:login' %}?next={{ request.get_full_path }}">Войти</a>
                    </li>
                    <li class="nav-item ms-3">
                        <a class="btn btn-info" href="{% url 'accounts:user_registration' %}?next={{ request.get_full_path }}">Регистрация</a>
                    </li>
                {% else %}
                    <li class="nav-item me-3">
                        <p>Привет <a href="{% url 'accounts:user_detail' user.pk %}">{{ user.username }}</a></p>
                    </li>
                    <li class="nav-item">
                        <a class="btn btn-info" href="{% url 'accounts:logout' %}?next={{ request.get_full_path }}">Выйти</a>
                    </li>
                    <li>
                        <button id="apiLogout">Logout</button>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/partial/pagination.html
<div class="pagination">
    <span class="step-links">
        <a href="?page=1">&laquo; В начало</a>
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">Назад</a>
        {% else %}
            <span class="page-disabled">Назад</span>
        {% endif %}

        <form class="current-page" method="get">
            <label for="page">
                Страница <input type="text" name="page" id="page" value="{{ page_obj.number }}">
                из {{ page_obj.paginator.num_pages }}.
            </label>
        </form>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Далее</a>
        {% else %}
            <span class="page-disabled">Далее</span>
        {% endif %}
        <a href="?page={{ page_obj.paginator.num_pages }}">В конец &raquo;</a>
    </span>
</div>

templates/partial/search_form.html
<form class="d-flex" role="search" method="GET">
    <input name="search" class="form-control me-2" type="search" placeholder="Найти" aria-label="Search">
    <button class="btn btn-outline-success" type="submit">Найти</button>
</form>